# Welcome to Jekyll!
#

# Site settings
title: faris.space
description: |
  random thoughts, musings, and art from
  a man with his head in the clouds
owner: faris chebib
first_published: 2016 # if migrating another site, the year of your first publish
email: faris@theluckybead.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://faris.space" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/siraf
  github: https://github.com/octaflop
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #facebook-official: https://facebook.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
